      Program Mean_conf
      implicit real*8 (a-h,o-z)

CCCCCCCCCCCCCCCCCCCCCCCCCCCCC
c  This code is for inserting the optimized crhomophore into the .gro file
c  to rerun the molecular Dynamic
CCCCCCCCCCCCCCCCCCCCCCCCCCCCC
c  5000 is the maximum number of atoms in the protein
c  ichromo( ,1) is the begining if the interval and ichromo( ,2) is the end
CCCCCCCCC

      character line21*21,line44*44,line11*11,line35*35,
     &line80*80,line27*27,line47*47,line126*126
      dimension coord(numero,3),ichromo(intervalos,2),
     &ichromog(500),itk2gro(numero),igro2tk(numero),
     &iqmintv(intervalos_qm,2),iqmatomsg(500),iqmatoms(500),
     &charges(500),fix(numero),Ncharges(500),charges0(500),
     &charges0tk(numero),charges0g(numero)
      open(1,file='final.xyz',status='old')
      open(2,file='template_tk2gro',status='old')
      open(3,file='template_gro2tk',status='old')
      open(4,file='Best_Config.gro',status='old')
      open(5,file='Best_Config_Ins.gro',status='unknown')
      open(6,file='Chromo.gro',status='unknown')
      open(7,file='charges.out',status='old')
      open(8,file='chain.itp_old',status='old')
      open(9,file='chain.itp',status='unknown')
C      open(10,file='temp',status='unknown')
      
CCCCCCCCC Number os atoms in the protein (numatoms)
      numatoms=numero
      iprotatoms=proatoms
      intervals=intervalos
      intervalsqm=intervalos_qm
CCCCCCCCC  Data (do not modify this label, it is used by the script)

CCCCCCCCC
C this section is for updating the geometry of the chromophore 
CCCCCCCCC
      read(1,*)
      read(2,*)
      read(3,*)
      
      do i=1,iprotatoms
         read(1,'(A11,f10.6,2x,f10.6,2x,f10.6)')line11,
     &        coord(i,1),coord(i,2),coord(i,3)
     
         read(2,'(8x,I6)')itk2gro(i)
         read(3,'(8x,I6)')igro2tk(i)
      enddo
      
      icont=0
      do i=1,intervals
         do j=ichromo(i,1),ichromo(i,2)
            icont=icont+1
            ichromog(icont)=itk2gro(j)
         enddo
      enddo

      read(4,*)
      read(4,*)
      write(5,'(A)')'Generated by Insert_Chromo'
      write(5,'(I5)')numatoms
      write(6,'(A)')'Generated by Insert_Chromo'
      write(6,'(I5)')icont

      do i=1,numatoms
         ipresent=0         
         do j=1,icont
            if (i.eq.ichromog(j)) then
               ipresent=j
            endif
         enddo
         
         if (ipresent.eq.0) then
            read(4,'(A44)')line44
            write(5,'(A44)')line44
         else
         read(4,'(A21)')line21
         write(5,'(A21,f7.3,1x,f7.3,1x,f7.3)')line21,
     &         coord(igro2tk(ichromog(ipresent)),1)/10.0d0,
     &         coord(igro2tk(ichromog(ipresent)),2)/10.0d0,
     &         coord(igro2tk(ichromog(ipresent)),3)/10.0d0            
         write(6,'(A21,f7.3,1x,f7.3,1x,f7.3)')line21,
     &         coord(igro2tk(ichromog(ipresent)),1)/10.0d0,
     &         coord(igro2tk(ichromog(ipresent)),2)/10.0d0,
     &         coord(igro2tk(ichromog(ipresent)),3)/10.0d0            
         endif
      enddo
      read(4,'(A40)')line44
      write(5,'(A40)')line44
      
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C this section is for updating the charges of the chromophore 
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCC  UPDATE, do not delete this label

      icont=0
      do i=1,intervalsqm
         do j=iqmintv(i,1),iqmintv(i,2)
            icont=icont+1
            iqmatoms(icont)=j
            iqmatomsg(icont)=itk2gro(j)
         enddo
      enddo

      ilastg=ultimo
      ifirstg=primero
      linefirst=linea

CCC Charges from the chain.itp (do not modify this label, it is used by the script)

      fixo=0.0d0
      init=1
      do i=ifirstg,ilastg
         ipresent=0
         do j=1,icont
            if (i.eq.iqmatomsg(j)) then
               ipresent=1
            endif
         enddo
         if (ipresent.eq.0) then
            fixo=fixo+fix(i)
         endif
      enddo
      Nfixo=nint(fixo*1000000)


C Reading the last obtained charges from molcas output

      do
         read(7,'(A80)',IOSTAT=io)line80
         if (io.gt.0) then
c            write(*,*) 'Check charges.out. Something was wrong'
            EXIT
         else if (io.eq.0) then
            k= index(line80,'Expectation values of the ESPF operators:')
            if (k.eq.7) then
               read(7,'(A80)')line80
               do i=1,icont
                  read(7,'(A35,f7.4)')line35,charges(i)
               enddo
            endif
         else if (io.lt.0) then
             goto 1
         endif
 1    enddo

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
c puting total charge exactly equal to 1

      do i=1,icont
         Ncharges(i)=nint(charges(i)*1000000)
      enddo
      k=sum(Ncharges)
c      write(*,*)k
 2    i=1
      do while (k.ne.1000000-Nfixo)
         if (k.gt.1000000-Nfixo) then
            Ncharges(i)=Ncharges(i)-1
         else
            Ncharges(i)=Ncharges(i)+1
         endif
         k=sum(Ncharges)
         i=i+1
      if (i.eq.icont+1) then
         goto 2
      endif 
      enddo
      do i=1,icont
         charges0(i)=Ncharges(i)/1000000.0d0
      enddo
      
      do i=1,icont
         charges0tk(iqmatoms(i))=charges0(i)
         charges0g(itk2gro(iqmatoms(i)))=charges0(i)
      enddo
      
      do i=1,icont
         fix(itk2gro(iqmatoms(i)))=charges0g(itk2gro(iqmatoms(i)))
      enddo

c      do i=ifirstg,ilastg
c         write(10,'(i4,2x,f9.6)')i,fix(i)
c      enddo
      
      do i=1,linefirst
         read(8,'(A)')line126
         write(9,'(A)')line126         
      enddo
      do i=ifirstg,ilastg
         read(8,'(A47,f9.6,A27)')line47,car,line27
         write(9,'(A47,f9.6,A27)')line47,fix(i),line27         
      enddo
      
      ifileend=finaltotal
      
      do i=(linefirst+(ilastg-ifirstg+1)+1),ifileend
         read(8,'(A)')line126
         write(9,'(A)')line126         
      enddo
      
   20 end
      


      
